[package]
name = "frib_datasource"
version = "0.1.0"
edition = "2024"

[dependencies]
nscldaq_ringbuffer = "0.8.8"
portman_client     = "0.2.0"
ringmaster_client  = "0.1.1"
rust_ringitem_format = "0.1.2"
url                 = "2.5.8"